backend:
    name: git-gateway
    branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://sxzar.com/assets/svgs/logo-black.svg
display_url: https://sxzar.com

media_folder: 'public/assets/images/work'
public_folder: '/assets/images/work'

collections:
    - name: 'work'
      label: 'Work'
      folder: 'src/content/work'
      create: true
      slug: '{{slug}}'
      preview_path: 'resources/{{slug}}'
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
          - { label: 'Task', name: 'task', widget: 'markdown' }
          - {
                label: 'Client',
                name: 'projectClient',
                widget: 'string',
                required: false
            }
          - {
                label: 'Project Date',
                name: 'projectDate',
                widget: 'datetime',
                required: false
            }
          - {
                label: 'Project URL',
                name: 'projectUrl',
                widget: 'string',
                required: false
            }
          - { label: 'Author', name: 'author', widget: 'string' }
          - { label: 'Date', name: 'date', widget: 'datetime' }
          - { label: 'Tags', name: 'tags', widget: 'list', default: ['post'] }
          - { label: 'Featured Image', name: 'image', widget: 'image' }
          - { label: 'Image Caption', name: 'imageAlt', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown', required: false }
