backend:
    name: git-gateway
    branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://sxzar.com/assets/svgs/logo-black.svg
display_url: https://sxzar.com

media_folder: "public/assets/images/resources"
public_folder: "/assets/images/resources"

collections:
    - name: "resources"
      label: "Resources"
      folder: "src/content/resources"
      create: true
      slug: "{{slug}}"
      preview_path: "resources/{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Short Title", name: "shortTitle", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
          - { label: "Featured Image", name: "image", widget: "image" }
          - {
                label: "Thumbnail",
                name: "thumbnail",
                widget: "image",
                hint: "max width of 400px"
            }
          - { label: "Image Caption", name: "imageAlt", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
